-- MERGE문
CREATE TABLE EX3_3 (
                       EMPLOYEE_ID NUMBER,
                       BONUS_AMT NUMBER DEFAULT 0
);

INSERT INTO EX3_3 (EMPLOYEE_ID)
SELECT E.EMPLOYEE_ID
FROM EMPLOYEES E, SALES S
WHERE E.EMPLOYEE_ID = S.EMPLOYEE_ID
  AND S.SALES_MONTH BETWEEN '200010' AND '200012'
GROUP BY E.EMPLOYEE_ID;

SELECT * FROM EX3_3 ORDER BY EMPLOYEE_ID;

SELECT EMPLOYEE_ID, MANAGER_ID, SALARY, SALARY * 0.01
FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM EX3_3);
