-- MERGE
CREATE TABLE EX3_3 (
                       EMPLOYEE_ID NUMBER,
                       BONUS_AMT NUMBER DEFAULT 0
);

INSERT INTO EX3_3 (EMPLOYEE_ID)
SELECT E.EMPLOYEE_ID
FROM EMPLOYEES E, SALES S
WHERE E.EMPLOYEE_ID = S.EMPLOYEE_ID
  AND S.SALES_MONTH BETWEEN '200010' AND '200012'
GROUP BY E.EMPLOYEE_ID;

SELECT * FROM EX3_3 ORDER BY EMPLOYEE_ID;

SELECT EMPLOYEE_ID, MANAGER_ID, SALARY, SALARY * 0.001
FROM EMPLOYEES
WHERE EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM EX3_3);

SELECT EMPLOYEE_ID, MANAGER_ID, SALARY, SALARY * 0.001
FROM EMPLOYEES
WHERE EMPLOYEE_ID NOT IN (SELECT EMPLOYEE_ID FROM EX3_3)
AND MANAGER_ID = 146;

MERGE INTO EX3_3 D
USING (SELECT EMPLOYEE_ID, SALARY, MANAGER_ID
       FROM EMPLOYEES
       WHERE MANAGER_ID = 146) B
ON (D.EMPLOYEE_ID = B.MANAGER_ID)
WHEN MATCHED THEN
    UPDATE
    SET D.BONUS_AMT = D.BONUS_AMT + B.SALARY * 0.01
WHEN NOT MATCHED THEN
    INSERT (D.EMPLOYEE_ID, D.BONUS_AMT)
    VALUES (B.EMPLOYEE_ID, B.SALARY * 0.001)
    WHERE (B.SALARY < 8000);

SELECT * FROM EX3_3 ORDER BY EMPLOYEE_ID;

MERGE INTO EX3_3 D
USING (SELECT EMPLOYEE_ID, SALARY, MANAGER_ID
       FROM EMPLOYEES
       WHERE MANAGER_ID = 146) B
ON (D.EMPLOYEE_ID = B.MANAGER_ID)
WHEN MATCHED THEN
    UPDATE
    SET D.BONUS_AMT = D.BONUS_AMT + B.SALARY * 0.01
    DELETE WHERE (B.EMPLOYEE_ID = 161)
WHEN NOT MATCHED THEN
    INSERT (D.EMPLOYEE_ID, D.BONUS_AMT)
    VALUES (B.EMPLOYEE_ID, B.SALARY * 0.001)
    WHERE (B.SALARY < 8000);

DELETE EX3_3;

SELECT partition_name FROM USER_TAB_PARTITIONS where table_name = 'SALES';

--의사컬럼
SELECT ROWNUM, EMPLOYEE_ID, ROWID
FROM EMPLOYEES WHERE ROWNUM < 5;

--문자 연산자
SELECT EMPLOYEE_ID || '@@@' || EMP_NAME as employee_info from EMPLOYEES where rownum < 5;

--CASE
SELECT EMPLOYEE_ID,
       SALARY,
       CASE
           WHEN SALARY <= 5000 THEN 'C등급'
           WHEN SALARY > 5000 AND SALARY <= 15000 THEN 'B등급'
           ELSE 'A등급'
           END AS SALARY_GRADE
FROM EMPLOYEES;

--ANY == SOME
SELECT EMPLOYEE_ID, SALARY
FROM EMPLOYEES
-- WHERE SALARY = ANY (2000, 3000, 4000)
WHERE SALARY = SOME (2000, 3000, 4000)
ORDER BY EMPLOYEE_ID;

--EXISTS
SELECT DEPARTMENT_ID, DEPARTMENT_NAME
FROM DEPARTMENTS a
WHERE EXISTS(SELECT *
             FROM EMPLOYEES b
             WHERE a.DEPARTMENT_ID = b.DEPARTMENT_ID
               AND b.SALARY > 3000)
ORDER BY a.DEPARTMENT_NAME;