--GROUP BY, HAVING
SELECT DEPARTMENT_ID, SUM(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID;

SELECT *
FROM KOR_LOAN_STATUS;

SELECT PERIOD, REGION, SUM(LOAN_JAN_AMT)
FROM KOR_LOAN_STATUS
WHERE PERIOD LIKE '2013%'
GROUP BY PERIOD, REGION
ORDER BY PERIOD, REGION;

SELECT PERIOD, REGION, SUM(LOAN_JAN_AMT)
FROM KOR_LOAN_STATUS
GROUP BY REGION, PERIOD
HAVING PERIOD = '201311'
ORDER BY REGION;


